Repository Fastcampus-Final-Team3/jober-frontend, pull requests merged in 2023-09, with the labels that each got.

#12 Design: 모달 레이아웃 UI 생성
  src/pages/wall/Wall.tsx
  src/pages/wall/components/modal/modalLayout.tsx
  src/pages/wall/components/modalInner.tsx
Labels: 완료된 작업

#14 Design: input focus시 나타나는 category List Layout
  src/pages/wall/components/categoryList.tsx
  src/pages/wall/components/categoryTemplate.tsx
Labels: 완료된 작업

#15 Feature: search template UI
  src/pages/wall/components/categoryList.tsx
  src/pages/wall/components/categoryTemplate.tsx
  src/pages/wall/components/modal/modalLayout.tsx
  src/pages/wall/components/modalInner.tsx
Labels: 완료된 작업

#20 Feature/zustand
  .gitignore
  package-lock.json
  package.json
  src/App.tsx
  src/assets/default.jpg
  src/assets/react.svg
  src/components/Layout.tsx
  src/data/constants/blocks.ts
  src/data/constants/wall.ts
  src/data/dummy/copy.db.json
  src/data/dummy/db.json
  src/index.css
  src/main.tsx
  src/pages/category/Category.tsx
  src/pages/home/Home.tsx
  src/pages/wall/Wall.tsx
  src/pages/wall/components/CategoryList.tsx
  src/pages/wall/components/CategoryTemplate.tsx
  src/pages/wall/components/ModalInner.tsx
  src/pages/wall/components/modal/ModalLayout.tsx
  src/store.ts
  src/types/blocks.ts
  src/types/wall.ts
  tsconfig.json
  vite.config.ts
Labels: 완료된 작업

#19 Feature:search template UI
  src/pages/wall/components/modal/ModalLayout.tsx
  src/pages/wall/components/modal/SearchTemplate.tsx
Labels: 완료된 작업

#23 Feature/all new folder
  src/App.tsx
  src/UIUX.tsx
  src/components/Layout.tsx
  src/components/category/Category.tsx
  src/components/category/index.ts
  src/components/home/Home.tsx
  src/components/home/index.ts
  src/components/index.ts
  src/components/wall/WallPage.tsx
  src/components/wall/blocks/BlockContainer.tsx
  src/components/wall/blocks/file/FileBlock.tsx
  src/components/wall/blocks/file/FileUpload.tsx
  src/components/wall/blocks/free/FreeBlock.tsx
  src/components/wall/blocks/index.ts
  src/components/wall/blocks/list/ListBlock.tsx
  src/components/wall/blocks/list/SingleList.tsx
  src/components/wall/blocks/profile/BackgroundImage.tsx
  src/components/wall/blocks/profile/ProfileBlock.tsx
  src/components/wall/blocks/profile/ProfileImage.tsx
  src/components/wall/blocks/sns/SnsBlock.tsx
  src/components/wall/blocks/sns/SnsBlockModal.tsx
  src/components/wall/blocks/template/Template.tsx
  src/components/wall/blocks/template/TemplateBlock.tsx
  src/components/wall/customization/index.ts
  src/components/wall/index.ts
  src/components/wall/templateModal/categoryInner/list/CategoryList.tsx
  src/components/wall/templateModal/categoryInner/listtemplate/CategoryTemplate.tsx
  src/components/wall/templateModal/index.ts
  src/components/wall/templateModal/layout/ModalLayout.tsx
  src/components/wall/templateModal/recommend/RecommendInner.tsx
  src/components/wall/templateModal/searchInner/SearchTemplate.tsx
  src/components/wall/wallLayout/AddBlockModal.tsx
  src/components/wall/wallLayout/WallHeader.tsx
  src/components/wall/wallLayout/WallHeaderAction.tsx
  src/components/wall/wallLayout/index.ts
  src/index.css
  src/pages/Category.tsx
  src/pages/Home.tsx
  src/pages/Wall.tsx
  src/pages/index.ts
  src/pages/wall/Wall.tsx
  src/pages/wall/WallHeader.tsx
  tailwind.config.js
  tsconfig.json
Labels: 완료된 작업

#24 Feature/all new folder
  package-lock.json
  package.json
  src/components/index.ts
  src/components/wall/WallPage.tsx
  src/components/wall/blocks/index.ts
  src/components/wall/blocks/profile/ProfileBlock.tsx
  src/components/wall/blocks/profile/ProfileImage.tsx
  src/main.tsx
  src/pages/App.tsx
  src/pages/Wall.tsx
  src/pages/index.ts
  vite.config.ts
Labels: 완료된 작업

#26 Feature/wall data restructuring
  src/components/wall/WallPage.tsx
  src/components/wall/blocks/BlockContainer.tsx
  src/components/wall/blocks/sns/SnsBlock.tsx
  src/data/dummy/copy.db.json
  src/data/dummy/db.json
  src/types/blocks.ts
  src/types/wall.ts
Labels: 작업 중

#28 Feature/wall header 디자인 및 일부 기능 #27
  src/assets/icons/close.svg
  src/assets/icons/export.svg
  src/assets/icons/input-suffix.svg
  src/assets/icons/more-vertical.svg
  src/assets/icons/notification.svg
  src/assets/icons/sms.svg
  src/assets/icons/user.svg
  src/components/wall/WallPage.tsx
  src/components/wall/wallLayout/WallHeader.tsx
  src/components/wall/wallLayout/WallHeaderAction.tsx
  src/components/wall/wallLayout/index.ts
  src/components/wall/wallLayout/wallHeader/ActionButton.tsx
  src/components/wall/wallLayout/wallHeader/WallHeader.tsx
  src/components/wall/wallLayout/wallHeader/WallHeaderAction.tsx
  src/components/wall/wallLayout/wallHeader/WallHeaderUser.tsx
  src/index.css
  src/pages/App.tsx
Labels: 완료된 작업

#30 Feature/profile block#29
  src/assets/icons/gallery.svg
  src/components/wall/WallPage.tsx
  src/components/wall/blocks/BlockContainer.tsx
  src/components/wall/blocks/profile/BackgroundImage.tsx
  src/components/wall/blocks/profile/ProfileBlock.tsx
  src/components/wall/blocks/profile/ProfileImage.tsx
  src/components/wall/wallLayout/wallHeader/WallHeader.tsx
  src/data/constants/wall.ts
  src/data/dummy/copy.db.json
  src/data/dummy/db.json
  src/pages/App.tsx
  src/types/wall.ts
  tailwind.config.js
Labels: 완료된 작업, 작업 중

#34 Feature/list block#31
  src/assets/default.jpg
  src/assets/icons/edit-thick.svg
  src/assets/icons/edit.svg
  src/assets/icons/plus.svg
  src/assets/icons/trash.svg
  src/components/wall/WallPage.tsx
  src/components/wall/blocks/BlockContainer.tsx
  src/components/wall/blocks/DragHandle.tsx
  src/components/wall/blocks/index.ts
  src/components/wall/blocks/list/ListBlock.tsx
  src/components/wall/blocks/list/SingleList.tsx
  src/components/wall/blocks/profile/BackgroundImage.tsx
  src/components/wall/blocks/profile/ProfileBlock.tsx
  src/components/wall/blocks/profile/ProfileImage.tsx
  src/components/wall/blocks/sns/SnsBlock.tsx
  src/components/wall/blocks/templates/Template.tsx
  src/components/wall/blocks/templates/TemplatesBlock.tsx
  src/components/wall/wallLayout/wallHeader/WallHeader.tsx
  src/components/wall/wallLayout/wallHeader/WallHeaderUser.tsx
  src/data/dummy/copy.db copy.json
  src/data/dummy/copy.db.json
  src/data/dummy/db.json
  src/index.css
  src/store.ts
  src/types/wall.ts
Labels: 작업 중

#36 Feature/21 customization modal UI #21
  src/assets/icons/customization/brush.svg
  src/components/wall/WallPage.tsx
  src/components/wall/customization/customizationInner/CustomizationModal.tsx
  src/components/wall/customization/index.ts
  src/components/wall/customization/layout/CustomizationLayout.tsx
  src/components/wall/index.ts
Labels: 완료된 작업

#43 Feature: 블록 삭제 기능
  src/components/wall/WallPage.tsx
  src/components/wall/blocks/BlockContainer.tsx
  src/components/wall/blocks/file/FileBlock.tsx
  src/components/wall/blocks/free/FreeBlock.tsx
  src/components/wall/blocks/list/ListBlock.tsx
  src/components/wall/blocks/sns/SnsBlock.tsx
  src/components/wall/blocks/templates/TemplatesBlock.tsx
  src/components/wall/wallLayout/addBlock/AddableBlock.tsx
  src/data/dummy/copy.db.json
Labels: 완료된 작업

#45 Feature/list block
  src/assets/icons/minus.svg
  src/components/Icon.tsx
  src/components/wall/blocks/list/ListBlock.tsx
  src/components/wall/blocks/list/SingleList.tsx
  src/data/dummy/db.json
  src/types/wall.ts
Labels: 완료된 작업

#46 Feature/sns block
  src/assets/icons/behance-logo.svg
  src/assets/icons/facebook-logo.svg
  src/assets/icons/github-logo.svg
  src/assets/icons/instagram-logo.svg
  src/assets/icons/linkedin-logo.svg
  src/components/Icon.tsx
  src/components/common/Icon.tsx
  src/components/common/ModalHeader.tsx
  src/components/common/index.ts
  src/components/wall/blocks/BlockContainer.tsx
  src/components/wall/blocks/list/ListBlock.tsx
  src/components/wall/blocks/list/SingleList.tsx
  src/components/wall/blocks/sns/SnsBlock.tsx
  src/components/wall/blocks/sns/SnsBlockModal.tsx
  src/components/wall/blocks/sns/SnsModalInput.tsx
  src/components/wall/wallLayout/addBlock/AddBlockModal.tsx
  src/data/constants/blocks.ts
  src/data/dummy/copy.db.json
  src/data/dummy/db.json
  src/types/wall.ts
Labels: 완료된 작업

#47 Feature: 자유 블록 기능
  src/components/wall/blocks/free/FreeBlock.tsx
  src/components/wall/blocks/list/ListBlock.tsx
  src/data/dummy/db.json
Labels: 완료된 작업

#48 Feature/customization modal inner#38
  src/components/wall/.DS_Store
  src/components/wall/WallPage.tsx
  src/components/wall/blocks/BlockContainer.tsx
  src/components/wall/customization/customizationInner/BackgroundSettings.tsx
  src/components/wall/customization/customizationInner/BlockSettings.tsx
  src/components/wall/customization/customizationInner/CustomizationModal.tsx
  src/components/wall/customization/customizationInner/ThemeSettings.tsx
  src/components/wall/customization/index.ts
  src/components/wall/customization/layout/CustomizationLayout.tsx
  src/data/constants/customization.ts
  src/index.css
Labels: 완료된 작업

#51 Feature/modal template
  categorydb.json
  list.json
  src/components/index.ts
  src/components/wall/templateModal/categoryInner/list/CategoryList.tsx
  src/components/wall/templateModal/categoryInner/listtemplate/CategoryTemplate.tsx
  src/components/wall/templateModal/layout/ModalLayout.tsx
  src/components/wall/wallLayout/WallHeaderAction.tsx
  src/pages/Category.tsx
  src/pages/Wall.tsx
  src/pages/index.ts
  walldb.json
Labels: 완료된 작업

#55 Feature/responsive
  src/assets/icons/github-logo.svg
  src/assets/icons/mobile-dropdown.svg
  src/components/wall/WallPage.tsx
  src/components/wall/blocks/BlockContainer.tsx
  src/components/wall/blocks/file/FileBlock.tsx
  src/components/wall/blocks/file/PdfPreview.tsx
  src/components/wall/blocks/free/FreeBlock.tsx
  src/components/wall/blocks/list/ListBlock.tsx
  src/components/wall/blocks/sns/SnsBlock.tsx
  src/components/wall/blocks/sns/SnsBlockModal.tsx
  src/components/wall/blocks/sns/SnsModalInput.tsx
  src/components/wall/blocks/templates/SingleTemplate.tsx
  src/components/wall/blocks/templates/TemplatesBlock.tsx
  src/components/wall/blocks/wallInfo/BackgroundImage.tsx
  src/components/wall/blocks/wallInfo/ProfileImage.tsx
  src/components/wall/blocks/wallInfo/WallInfoBlock.tsx
  src/components/wall/customization/Customization.tsx
  src/components/wall/wallLayout/addBlock/AddBlockButton.tsx
  src/components/wall/wallLayout/addBlock/AddableBlock.tsx
  src/components/wall/wallLayout/wallHeader/ActionButton.tsx
  src/components/wall/wallLayout/wallHeader/MobileFixedFooter.tsx
  src/components/wall/wallLayout/wallHeader/WallHeader.tsx
  src/components/wall/wallLayout/wallHeader/WallHeaderAction.tsx
  src/components/wall/wallLayout/wallHeader/WallHeaderInput.tsx
  src/components/wall/wallLayout/wallHeader/WallHeaderSavigButtons.tsx
  src/components/wall/wallLayout/wallHeader/WallHeaderUser.tsx
  src/data/constants/blocks.ts
  src/data/dummy/db.json
  src/hooks/useFetchWallData.ts
  src/hooks/useWindowWidth.ts
  src/index.css
Labels: 작업 중

#56 Feature/modal contents
  src/components/wall/templateModal/categoryInner/list/CategoryList.tsx
  src/components/wall/templateModal/categoryInner/listtemplate/CategoryTemplate.tsx
  src/components/wall/templateModal/layout/ModalLayout.tsx
  src/components/wall/templateModal/searchInner/SearchTemplate.tsx
  src/data/dummy/db.json
Labels: 완료된 작업

#59 # 서버 통신 react-query 변경, radio기능 추가
  src/components/wall/templateModal/recommend/RecommendInner.tsx
  vite.config.ts
Labels: 완료된 작업

#60 Feat: 선택한 radio 버튼 템플릿 데이터 전역 상태 관리를 위한 store 생성
  src/store.ts
Labels: 완료된 작업
